version: '3.1'

services:
  bot:
    build: ./bot
    restart: always
    depends_on:
      - img_handler
    environment:
      TG_BOT_TOKEN: "Your_telegram_token_bot"
      EDIT_IMAGES_HOST: img_handler

  web:
    build: ./web
    restart: always
    depends_on:
      - img_handler
    environment:
      EDIT_IMAGES_HOST: img_handler
    ports:
      # Your port (default: 8088)
      - "127.0.0.1:8088:80"

  img_handler:
    build: ./img_handler
    restart: always
    environment:
      # Models
      # u2net: A pre-trained model for general use cases.
      # u2netp: A lightweight version of u2net model.
      # u2net_human_seg: A pre-trained model for human segmentation.
      # u2net_cloth_seg: A pre-trained model for Cloths Parsing from human portrait. Here clothes are parsed into 3 category: Upper body, Lower body and Full body.
      # silueta: Same as u2net but the size is reduced to 43Mb.
      MODEL: "u2netp"
    ports:
      - "8080"

    # You can limit resources, be careful. Recommended 700M.
    # deploy:
    #  resources:
    #    limits:
    #      memory: 350M
